### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [kenklak/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Really nice job on this project, end result looks good. Your code was very organized and well thought out. I created some small issues you should look at and implement as they will help you moving forward. Overall very nice job, you are ready for the next sections.
https://www.codecademy.com/articles/accessibility

**Comment by kenklak** [comment]
Hey there. I changed the code as you suggested. Thanks for those suggestions. I did receive an email stating that the review was done, however, the Review section has still not been 'tagged' as completed, so the step always shows as not completed. Does that matter?
